-- Purpose: SQL Editor-safe forward fix for analytics logs + subscription idempotency.
-- Safety: idempotent, SQL Editor safe
-- Affected objects: public.analytics_logs, public.subscriptions, public.notifications
-- Risks (tier): Medium
-- Rollback plan: Drop created indexes/policies by exact name if required.

-- Block 1: Ensure analytics_logs exists
DO $$
BEGIN
  IF to_regclass('public.analytics_logs') IS NULL THEN
    CREATE TABLE public.analytics_logs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      event_type TEXT NOT NULL,
      user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
      data JSONB NOT NULL DEFAULT '{}'::jsonb,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS analytics_logs_created_at_idx
  ON public.analytics_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS analytics_logs_event_type_idx
  ON public.analytics_logs (event_type);
CREATE INDEX IF NOT EXISTS analytics_logs_user_id_idx
  ON public.analytics_logs (user_id);

-- Block 2: Forward-fix subscriptions/notifications idempotency
CREATE INDEX IF NOT EXISTS idx_subscriptions_venue_id
  ON public.subscriptions (venue_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_stripe_id
  ON public.subscriptions (stripe_subscription_id);
CREATE INDEX IF NOT EXISTS idx_notifications_visitor_id
  ON public.notifications (visitor_id);

-- Block 3: Post-check snapshot
SELECT
  to_regclass('public.analytics_logs') IS NOT NULL AS analytics_logs_exists,
  to_regclass('public.subscriptions') IS NOT NULL AS subscriptions_exists,
  to_regclass('public.notifications') IS NOT NULL AS notifications_exists;

