-- ==========================================
-- 0007: Buildings & Floor Plans
-- ==========================================

-- 1. Create or Update Buildings Table
CREATE TABLE IF NOT EXISTS public.buildings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    location GEOGRAPHY(POINT, 4326),
    address TEXT,
    province TEXT,
    total_floors INTEGER DEFAULT 1,

    -- Floor Mapping: JSONB structure
    -- {
    --   "1": { "name": "G", "shops": [id1, id2], "plan_url": "..." },
    --   "2": { "name": "2F", "shops": [id3], "plan_url": "..." }
    -- }
    floors JSONB DEFAULT '{}'::JSONB,

    metadata JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS buildings_location_idx ON public.buildings USING GIST(location);

-- 2. Link Venues to Buildings
ALTER TABLE public.venues
    ADD COLUMN IF NOT EXISTS building_id BIGINT REFERENCES public.buildings(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS floor_number TEXT; -- e.g. "G", "1", "B1"

CREATE INDEX IF NOT EXISTS venues_building_id_idx ON public.venues(building_id);

-- 3. RPC: Get Building Details with Shops
CREATE OR REPLACE FUNCTION public.get_building_details(p_building_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_building JSONB;
    v_shops JSONB;
BEGIN
    -- Get Building Info
    SELECT row_to_json(b)::jsonb INTO v_building
    FROM public.buildings b
    WHERE id = p_building_id;

    IF v_building IS NULL THEN
        RETURN NULL;
    END IF;

    -- Get Shops in Building
    SELECT jsonb_agg(
        jsonb_build_object(
            'id', v.id,
            'name', v.name,
            'category', v.category,
            'floor', v.floor_number,
            'pin_type', v.pin_type,
            'image', v.image_urls[1] -- Cover image
        )
    ) INTO v_shops
    FROM public.venues v
    WHERE v.building_id = p_building_id AND v.status = 'active';

    -- Merge
    RETURN v_building || jsonb_build_object('shops', COALESCE(v_shops, '[]'::jsonb));
END;
$$;

-- RLS
ALTER TABLE public.buildings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read buildings" ON public.buildings FOR SELECT USING (true);
CREATE POLICY "Service role manages buildings" ON public.buildings FOR ALL TO service_role USING (true);
