/**
 * Property-Based Test: HSL Color Constraints
 * 
 * **Validates: Requirements 2.3, 7.1, 11.1**
 * 
 * This test validates Property 9: HSL Color Constraints
 * 
 * Property Statement:
 * For any generated neon color, the HSL values should satisfy:
 * - Saturation ∈ [70, 100]
 * - Lightness ∈ [50, 70]
 * 
 * This property ensures that all colors generated by the Category Color Engine
 * meet the design constraints for optimal visibility on dark backgrounds and
 * maintain the vibrant neon aesthetic.
 */

import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import {
  generateColorAtIndex,
  generateNeonColors,
} from '@/lib/neon/color-engine';

describe('Property 9: HSL Color Constraints', () => {
  describe('generateColorAtIndex', () => {
    it('should always generate colors with saturation in [70, 100] range', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 0, max: 100 }), // Test with various indices
          (index) => {
            const color = generateColorAtIndex(index);
            
            // Property: Saturation must be within [70, 100]
            expect(color.hsl.s).toBeGreaterThanOrEqual(70);
            expect(color.hsl.s).toBeLessThanOrEqual(100);
          }
        ),
        { numRuns: 100 } // Run 100 iterations as specified in requirements
      );
    });

    it('should always generate colors with lightness in [50, 70] range', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 0, max: 100 }),
          (index) => {
            const color = generateColorAtIndex(index);
            
            // Property: Lightness must be within [50, 70]
            expect(color.hsl.l).toBeGreaterThanOrEqual(50);
            expect(color.hsl.l).toBeLessThanOrEqual(70);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should satisfy both saturation and lightness constraints simultaneously', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 0, max: 100 }),
          (index) => {
            const color = generateColorAtIndex(index);
            
            // Property: Both constraints must hold simultaneously
            const saturationValid = color.hsl.s >= 70 && color.hsl.s <= 100;
            const lightnessValid = color.hsl.l >= 50 && color.hsl.l <= 70;
            
            expect(saturationValid).toBe(true);
            expect(lightnessValid).toBe(true);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should respect custom saturation range configuration', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 0, max: 100 }),
          fc.integer({ min: 70, max: 90 }), // Custom min saturation
          fc.integer({ min: 80, max: 100 }), // Custom max saturation
          (index, minSat, maxSat) => {
            // Ensure min <= max
            const [min, max] = minSat <= maxSat ? [minSat, maxSat] : [maxSat, minSat];
            
            const config = {
              saturationRange: [min, max] as [number, number],
              lightnessRange: [50, 70] as [number, number],
            };
            
            const color = generateColorAtIndex(index, config);
            
            // Property: Generated color respects custom saturation range
            expect(color.hsl.s).toBeGreaterThanOrEqual(min);
            expect(color.hsl.s).toBeLessThanOrEqual(max);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should respect custom lightness range configuration', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 0, max: 100 }),
          fc.integer({ min: 50, max: 60 }), // Custom min lightness
          fc.integer({ min: 60, max: 70 }), // Custom max lightness
          (index, minLight, maxLight) => {
            // Ensure min <= max
            const [min, max] = minLight <= maxLight ? [minLight, maxLight] : [maxLight, minLight];
            
            const config = {
              saturationRange: [70, 100] as [number, number],
              lightnessRange: [min, max] as [number, number],
            };
            
            const color = generateColorAtIndex(index, config);
            
            // Property: Generated color respects custom lightness range
            expect(color.hsl.l).toBeGreaterThanOrEqual(min);
            expect(color.hsl.l).toBeLessThanOrEqual(max);
          }
        ),
        { numRuns: 100 }
      );
    });
  });

  describe('generateNeonColors', () => {
    it('should generate all colors with saturation in [70, 100] range', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 1, max: 20 }), // Test with various batch sizes
          (count) => {
            const colors = generateNeonColors(count);
            
            // Property: All colors must have saturation within [70, 100]
            colors.forEach((color, index) => {
              expect(color.hsl.s).toBeGreaterThanOrEqual(70);
              expect(color.hsl.s).toBeLessThanOrEqual(100);
            });
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should generate all colors with lightness in [50, 70] range', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 1, max: 20 }),
          (count) => {
            const colors = generateNeonColors(count);
            
            // Property: All colors must have lightness within [50, 70]
            colors.forEach((color, index) => {
              expect(color.hsl.l).toBeGreaterThanOrEqual(50);
              expect(color.hsl.l).toBeLessThanOrEqual(70);
            });
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should generate all colors satisfying both constraints', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 1, max: 20 }),
          (count) => {
            const colors = generateNeonColors(count);
            
            // Property: Every color must satisfy both constraints
            colors.forEach((color) => {
              const saturationValid = color.hsl.s >= 70 && color.hsl.s <= 100;
              const lightnessValid = color.hsl.l >= 50 && color.hsl.l <= 70;
              
              expect(saturationValid && lightnessValid).toBe(true);
            });
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should respect custom configuration for all generated colors', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 1, max: 15 }),
          fc.integer({ min: 75, max: 85 }), // Custom saturation min
          fc.integer({ min: 85, max: 95 }), // Custom saturation max
          fc.integer({ min: 52, max: 58 }), // Custom lightness min
          fc.integer({ min: 58, max: 68 }), // Custom lightness max
          (count, minSat, maxSat, minLight, maxLight) => {
            // Ensure min <= max for both ranges
            const [satMin, satMax] = minSat <= maxSat ? [minSat, maxSat] : [maxSat, minSat];
            const [lightMin, lightMax] = minLight <= maxLight ? [minLight, maxLight] : [maxLight, minLight];
            
            const config = {
              saturationRange: [satMin, satMax] as [number, number],
              lightnessRange: [lightMin, lightMax] as [number, number],
              minDeltaE: 30,
            };
            
            const colors = generateNeonColors(count, config);
            
            // Property: All colors respect custom configuration
            colors.forEach((color) => {
              expect(color.hsl.s).toBeGreaterThanOrEqual(satMin);
              expect(color.hsl.s).toBeLessThanOrEqual(satMax);
              expect(color.hsl.l).toBeGreaterThanOrEqual(lightMin);
              expect(color.hsl.l).toBeLessThanOrEqual(lightMax);
            });
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should maintain constraints even with large batch sizes', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 20, max: 25 }), // Cap at 25 to avoid timeout
          (count) => {
            const colors = generateNeonColors(count);
            
            // Property: Constraints hold even for large batches
            colors.forEach((color) => {
              expect(color.hsl.s).toBeGreaterThanOrEqual(70);
              expect(color.hsl.s).toBeLessThanOrEqual(100);
              expect(color.hsl.l).toBeGreaterThanOrEqual(50);
              expect(color.hsl.l).toBeLessThanOrEqual(70);
            });
          }
        ),
        { numRuns: 5 } // Reduced from 50 — large batches are expensive
      );
    });
  });

  describe('Edge Cases', () => {
    it('should handle index 0 correctly', () => {
      const color = generateColorAtIndex(0);
      
      expect(color.hsl.s).toBeGreaterThanOrEqual(70);
      expect(color.hsl.s).toBeLessThanOrEqual(100);
      expect(color.hsl.l).toBeGreaterThanOrEqual(50);
      expect(color.hsl.l).toBeLessThanOrEqual(70);
    });

    it('should handle very large indices', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 1000, max: 10000 }),
          (index) => {
            const color = generateColorAtIndex(index);
            
            expect(color.hsl.s).toBeGreaterThanOrEqual(70);
            expect(color.hsl.s).toBeLessThanOrEqual(100);
            expect(color.hsl.l).toBeGreaterThanOrEqual(50);
            expect(color.hsl.l).toBeLessThanOrEqual(70);
          }
        ),
        { numRuns: 50 }
      );
    });

    it('should handle minimum batch size (1 color)', () => {
      const colors = generateNeonColors(1);
      
      expect(colors).toHaveLength(1);
      expect(colors[0].hsl.s).toBeGreaterThanOrEqual(70);
      expect(colors[0].hsl.s).toBeLessThanOrEqual(100);
      expect(colors[0].hsl.l).toBeGreaterThanOrEqual(50);
      expect(colors[0].hsl.l).toBeLessThanOrEqual(70);
    });

    it('should handle boundary values for saturation range', () => {
      const configMin = {
        saturationRange: [70, 70] as [number, number],
        lightnessRange: [50, 70] as [number, number],
      };
      
      const configMax = {
        saturationRange: [100, 100] as [number, number],
        lightnessRange: [50, 70] as [number, number],
      };
      
      const colorMin = generateColorAtIndex(0, configMin);
      const colorMax = generateColorAtIndex(0, configMax);
      
      // Should handle exact boundary values
      expect(colorMin.hsl.s).toBeGreaterThanOrEqual(70);
      expect(colorMin.hsl.s).toBeLessThanOrEqual(70);
      expect(colorMax.hsl.s).toBeGreaterThanOrEqual(100);
      expect(colorMax.hsl.s).toBeLessThanOrEqual(100);
    });

    it('should handle boundary values for lightness range', () => {
      const configMin = {
        saturationRange: [70, 100] as [number, number],
        lightnessRange: [50, 50] as [number, number],
      };
      
      const configMax = {
        saturationRange: [70, 100] as [number, number],
        lightnessRange: [70, 70] as [number, number],
      };
      
      const colorMin = generateColorAtIndex(0, configMin);
      const colorMax = generateColorAtIndex(0, configMax);
      
      // Should handle exact boundary values
      expect(colorMin.hsl.l).toBeGreaterThanOrEqual(50);
      expect(colorMin.hsl.l).toBeLessThanOrEqual(50);
      expect(colorMax.hsl.l).toBeGreaterThanOrEqual(70);
      expect(colorMax.hsl.l).toBeLessThanOrEqual(70);
    });
  });
});
