-- Enable Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "postgis";
CREATE EXTENSION IF NOT EXISTS "pg_cron";
CREATE EXTENSION IF NOT EXISTS "pg_net";

-- 1. Profiles (Users)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT,
    username TEXT UNIQUE,
    full_name TEXT,
    avatar_url TEXT,
    coins INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
    FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." ON public.profiles
    FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

-- 2. Shops (Venues)
CREATE TABLE public.shops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT,
    sub_categories TEXT[],
    description TEXT,
    address TEXT,
    province TEXT,
    district TEXT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    location GEOGRAPHY(POINT, 4326),
    images TEXT[],
    opening_hours JSONB,
    price_level INTEGER DEFAULT 1,
    rating DOUBLE PRECISION DEFAULT 0,
    review_count INTEGER DEFAULT 0,
    status TEXT DEFAULT 'active', -- active, closed, pending
    is_verified BOOLEAN DEFAULT false,
    owner_id UUID REFERENCES public.profiles(id),
    social_links JSONB,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    scraped_at TIMESTAMP WITH TIME ZONE,
    source_url TEXT
);
CREATE INDEX shops_location_idx ON public.shops USING GIST(location);
ALTER TABLE public.shops ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Shops are viewable by everyone." ON public.shops
    FOR SELECT USING (true);

CREATE POLICY "Owners can update their shops." ON public.shops
    FOR UPDATE USING (auth.uid() = owner_id);

-- 3. Shop Photos (UGC)
CREATE TABLE public.shop_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT REFERENCES public.shops(id) ON DELETE CASCADE,
    uploader_id UUID REFERENCES public.profiles(id),
    url TEXT NOT NULL,
    caption TEXT,
    is_featured BOOLEAN DEFAULT false,
    status TEXT DEFAULT 'pending', -- pending, approved, rejected
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.shop_photos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Photos are viewable by everyone." ON public.shop_photos
    FOR SELECT USING (status = 'approved' OR auth.uid() = uploader_id);

CREATE POLICY "Users can upload photos." ON public.shop_photos
    FOR INSERT WITH CHECK (auth.uid() = uploader_id);

-- 4. Reviews
CREATE TABLE public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT REFERENCES public.shops(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.profiles(id),
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    text TEXT,
    images TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Reviews are viewable by everyone." ON public.reviews
    FOR SELECT USING (true);

CREATE POLICY "Users can create reviews." ON public.reviews
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 5. Shop Coins (Inventory)
CREATE TABLE public.shop_coins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT REFERENCES public.shops(id) ON DELETE CASCADE,
    amount INTEGER DEFAULT 0, -- Coins available to be collected
    max_per_day INTEGER DEFAULT 10,
    refresh_rate INTEGER DEFAULT 1, -- Coins added per hour
    last_refill_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE public.shop_coins ENABLE ROW LEVEL SECURITY;

-- 6. User Coin Transactions (Ledger)
CREATE TABLE public.user_coin_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    amount INTEGER NOT NULL, -- Positive for gain, negative for spend
    transaction_type TEXT NOT NULL, -- checkin, review, photo, redeem, bonus
    reference_id TEXT, -- e.g., shop_id or coupon_id
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.user_coin_ledger ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own ledger." ON public.user_coin_ledger
    FOR SELECT USING (auth.uid() = user_id);

-- 7. Coupons (Redemption)
CREATE TABLE public.coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT REFERENCES public.shops(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    cost INTEGER NOT NULL,
    image_url TEXT,
    stock INTEGER DEFAULT -1, -- -1 for infinite
    status TEXT DEFAULT 'active',
    valid_until TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Coupons are viewable by everyone." ON public.coupons
    FOR SELECT USING (status = 'active');

-- 8. User Coupons (Redeemed)
CREATE TABLE public.user_coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    coupon_id BIGINT REFERENCES public.coupons(id),
    code TEXT NOT NULL,
    status TEXT DEFAULT 'valid', -- valid, used, expired
    redeemed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    used_at TIMESTAMP WITH TIME ZONE
);
ALTER TABLE public.user_coupons ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own coupons." ON public.user_coupons
    FOR SELECT USING (auth.uid() = user_id);

-- 9. Analytics Logs
CREATE TABLE public.analytics_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL, -- view_shop, search, filter, click_coin
    user_id UUID, -- Nullable for anon
    data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- No RLS, only accessible by service role/admin API

-- 10. Webhooks
CREATE TABLE public.webhooks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL,
    event_types TEXT[],
    secret TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 11. Push Subscriptions
CREATE TABLE public.push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    token TEXT NOT NULL,
    platform TEXT, -- web, android, ios
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, token)
);
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own subscriptions." ON public.push_subscriptions
    FOR ALL USING (auth.uid() = user_id);

-- Auto-update updated_at function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_profiles_modtime BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_shops_modtime BEFORE UPDATE ON public.shops FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 12. User Stats (Gamification)
CREATE TABLE public.user_stats (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
    xp INTEGER DEFAULT 0,
    level INTEGER DEFAULT 1,
    coins INTEGER DEFAULT 0,
    submissions_count INTEGER DEFAULT 0,
    check_ins_count INTEGER DEFAULT 0,
    photos_count INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.user_stats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public stats" ON public.user_stats FOR SELECT USING (true);
CREATE POLICY "System update stats" ON public.user_stats FOR ALL USING (auth.uid() = user_id); -- Simplified for MVP

-- 13. User Submissions (Pending Shops)
CREATE TABLE public.user_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    name TEXT,
    category TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    province TEXT,
    images TEXT[],
    description TEXT,
    status TEXT DEFAULT 'pending', -- pending, approved, rejected
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.user_submissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users view own submissions" ON public.user_submissions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users create submissions" ON public.user_submissions FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 14. Check-ins
CREATE TABLE public.check_ins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    venue_id BIGINT REFERENCES public.shops(id), -- Assuming 'shops' table is 'venues' in code? Code/Schema mismatch check later.
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.check_ins ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users check in" ON public.check_ins FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 15. Venue Photos (UGC) - Aliasing/Replacing shop_photos logic
CREATE TABLE public.venue_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    venue_id BIGINT REFERENCES public.shops(id),
    image_url TEXT NOT NULL,
    caption TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.venue_photos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public venue photos" ON public.venue_photos FOR SELECT USING (status = 'approved');
CREATE POLICY "Users upload venue photos" ON public.venue_photos FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 16. User Achievements
CREATE TABLE public.user_achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    badge_code TEXT,
    awarded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.user_achievements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public achievements" ON public.user_achievements FOR SELECT USING (true);
