/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/v1/shops": {
		get: {
			responses: {
				200: {
					content: {
						"application/json": components["schemas"]["Venue"][];
					};
				};
			};
		};
	};
}

export interface components {
	schemas: {
		Venue: {
			id: string;
			name: string;
			lat: number;
			lng: number;
			category?: string;
			is_live?: boolean;
		};
	};
}
