-- Analytics Tables for VibeCity
-- Optimized for high-volume ingest without requiring user login for every event

CREATE TABLE IF NOT EXISTS public.analytics_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    visitor_id TEXT NOT NULL, -- Fingerprint or Cookie ID
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    user_agent TEXT,
    ip_hash TEXT, -- Anonymized IP
    country TEXT,
    city TEXT,
    device_type TEXT, -- mobile, desktop, tablet
    referrer TEXT,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_analytics_sessions_visitor ON public.analytics_sessions(visitor_id);
CREATE INDEX idx_analytics_sessions_user ON public.analytics_sessions(user_id);

CREATE TABLE IF NOT EXISTS public.analytics_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID REFERENCES public.analytics_sessions(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL, -- e.g., 'view_shop', 'click_phone', 'search', 'filter'
    shop_id BIGINT REFERENCES public.shops(id) ON DELETE SET NULL,
    metadata JSONB DEFAULT '{}'::JSONB, -- Extra data: e.g., { "search_term": "sushi" }
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Partitioning could be considered for events table if scale is massive, but standard table for MVP.
CREATE INDEX idx_analytics_events_shop ON public.analytics_events(shop_id);
CREATE INDEX idx_analytics_events_type ON public.analytics_events(event_type);
CREATE INDEX idx_analytics_events_created ON public.analytics_events(created_at);

-- RLS: Service Role only for inserting (via Edge Function)
-- Users shouldn't read raw analytics directly, only aggregated views via RPC (later)
ALTER TABLE public.analytics_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role can manage analytics" ON public.analytics_sessions
    FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Service role can manage events" ON public.analytics_events
    FOR ALL TO service_role USING (true) WITH CHECK (true);
