// NOTE: Rsbuild serves `/public/sw.js` in production.
// This module is kept for legacy bundlers that inject __WB_MANIFEST.
import { clientsClaim } from "workbox-core";
import { ExpirationPlugin } from "workbox-expiration";
import { cleanupOutdatedCaches, precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import {
	CacheFirst,
	NetworkFirst,
	StaleWhileRevalidate,
} from "workbox-strategies";

clientsClaim();
cleanupOutdatedCaches();

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Cache Google Fonts
registerRoute(
	({ url }) =>
		url.origin === "https://fonts.googleapis.com" ||
		url.origin === "https://fonts.gstatic.com",
	new StaleWhileRevalidate({
		cacheName: "google-fonts",
		plugins: [new ExpirationPlugin({ maxEntries: 20 })],
	}),
);

// Cache Mapbox Tiles (aggressive caching)
registerRoute(
	({ url }) => url.origin.includes("mapbox.com"),
	new CacheFirst({
		cacheName: "mapbox-tiles",
		plugins: [
			new ExpirationPlugin({
				maxEntries: 500,
				maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
			}),
		],
	}),
);

// Cache Supabase Storage Images (StaleWhileRevalidate)
registerRoute(
	({ url }) =>
		url.origin.includes("supabase.co") &&
		url.pathname.includes("/storage/v1/object/public/"),
	new StaleWhileRevalidate({
		cacheName: "supabase-images",
		plugins: [
			new ExpirationPlugin({
				maxEntries: 100,
				maxAgeSeconds: 7 * 24 * 60 * 60, // 7 Days
			}),
		],
	}),
);

// Cache Database API Requests (NetworkFirst - fresh data is priority)
registerRoute(
	({ url }) =>
		url.origin.includes("supabase.co") && url.pathname.includes("/rest/v1/"),
	new NetworkFirst({
		cacheName: "api-data",
		plugins: [
			new ExpirationPlugin({
				maxEntries: 50,
				maxAgeSeconds: 24 * 60 * 60, // 24 Hours
			}),
		],
	}),
);

self.addEventListener("message", (event) => {
	if (event.data && event.data.type === "SKIP_WAITING") {
		self.skipWaiting();
	}
});
