-- Purpose: Ensure analytics_logs exists in active migration chain.
-- Safety: idempotent, SQL Editor safe
-- Affected objects: public.analytics_logs
-- Risks (tier): Medium
-- Rollback plan: Keep table; if accidental, soft-disable writers first then archive data.

DO $$
BEGIN
  IF to_regclass('public.analytics_logs') IS NULL THEN
    CREATE TABLE public.analytics_logs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      event_type TEXT NOT NULL,
      user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
      data JSONB NOT NULL DEFAULT '{}'::jsonb,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS analytics_logs_created_at_idx
  ON public.analytics_logs (created_at DESC);

CREATE INDEX IF NOT EXISTS analytics_logs_event_type_idx
  ON public.analytics_logs (event_type);

CREATE INDEX IF NOT EXISTS analytics_logs_user_id_idx
  ON public.analytics_logs (user_id);

