-- ==========================================
-- 0002: orders and payments
-- ==========================================

-- 1) Order Status Enum
do $$ begin
  if not exists (select 1 from pg_type where typname = 'order_status') then
    create type order_status as enum ('pending', 'paid', 'failed', 'refunded');
  end if;
end $$;

-- 2) Orders Table
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id),
  shop_id bigint references public.shops(id), -- Optional: if purchasing for a specific shop

  provider text not null default 'stripe',
  provider_order_id text, -- e.g., Stripe Session ID

  status order_status not null default 'pending',
  total_amount numeric(10,2) not null default 0,
  currency text not null default 'THB',

  metadata jsonb default '{}'::jsonb,

  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3) Order Items
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid references public.orders(id) on delete cascade,
  sku text not null,
  quantity int not null default 1,
  price numeric(10,2) not null default 0
);

-- 4) Payment Events (Audit Log)
create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  order_id uuid references public.orders(id) on delete set null,
  event_type text not null, -- e.g. 'checkout.session.completed'
  provider_event_id text,
  payload jsonb,
  created_at timestamptz default now()
);

-- 5) Indexes/RLS
create index if not exists orders_user_id_idx on public.orders(user_id);
create index if not exists orders_shop_id_idx on public.orders(shop_id);
create index if not exists orders_provider_order_id_idx on public.orders(provider_order_id);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payment_events enable row level security;

-- Policy: Users can view their own orders
create policy "Users view own orders" on public.orders
  for select using (auth.uid() = user_id);

-- Policy: Service Role (Edge Functions) has full access
create policy "Service role full access orders" on public.orders
  for all using (true) with check (true);
  -- Note: In Supabase, service_role bypasses RLS, but explicit policies can document intent.
  -- Real constraint is preventing other users from writing.
